services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=stdm-lab-3
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stdm-lab-3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d stdm-lab-3" ]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
